name: disease_risk_app
description: A practical student prototype for hybrid quantum heart-disease classification
publish_to: "none"
version: 2.0.0+2
environment:
  sdk: ">=3.10.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  file_selector: ^1.1.0
  pdf: ^3.12.0
  printing: ^5.14.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
